In [ ]:
import pandas as pd 

df = pd.read_csv("orders.csv")
print(df)

In [ ]:
df.head() 
# first rows of the dataframe 
# default = 5

In [ ]:
df.tail()
# last rows of the dataframe
# default = 5

In [4]:
df.info()
# general information on the dataframe
# column names and types , count  ...

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       40 non-null     int64
 1   CustomerName  40 non-null     str
 2   Product       40 non-null     str
 3   Category      40 non-null     str
 4   Quantity      40 non-null     int64
 5   Price         40 non-null     float64
 6   OrderDate     40 non-null     str
 7   Shipped       40 non-null     str
 8   Country       40 non-null     str
dtypes: float64(1), int64(2), str(6)
memory usage: 2.9 KB

In [ ]:
df.describe()
# Descriptive statistics about the dataframe's columns

           OrderID    Quantity        Price
count    40.000000   40.000000    40.000000
mean   1020.500000    5.450000   106.457500
std      11.690452   15.903475   201.091854
min    1001.000000    1.000000     0.800000
25%    1010.750000    1.000000    18.000000
50%    1020.500000    1.000000    43.500000
75%    1030.250000    2.250000   112.500000
max    1040.000000  100.000000  1200.000000

In [ ]:
df.columns
# Dtatframe's columns

Index(['OrderID', 'CustomerName', 'Product', 'Category', 'Quantity', 'Price',
       'OrderDate', 'Shipped', 'Country'],
      dtype='str')

In [ ]:
# INDEXING ROWS / COLUMNS

In [ ]:
df["Product"]
# set(df["Product"]) , print all unique values (a set)
# index all the values inside the column
# returns a Series

In [12]:
# ROW indexing
df.iloc[0]
# index location

OrderID                1001
CustomerName     John Smith
Product              Laptop
Category        Electronics
Quantity                  1
Price                1200.0
OrderDate        2024-06-01
Shipped                 Yes
Country                 USA
Name: 0, dtype: object

In [13]:
 # Access specific values in the row 

df.iloc[10]["Country"]

'France'

In [17]:
# Filtering 

df[(df["Country"] == 'USA' ) & (df["Category"] != "Electronics") ]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA

In [32]:
# Advanced filtering 

df[df["CustomerName"].str.startswith("Z")]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan

In [ ]:
df[df["Country"].isin(["Sweeden" , "France" , "Germany"])]

In [ ]:
# tilda operator : ~ 
# if we add the operator in the begining of the filter , it's negation will be considered (the inverse)
df[~df["Country"].isin(["Sweeden" , "France" , "Germany"])]

In [ ]:
#Updating Data

In [ ]:
# locating based on a label 
# a label being any antry in a row 

df.loc[df["CustomerName"] == "Anna Ivanova"]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [36]:
# Changing a value after loc 

df.loc[df["CustomerName"] == "Yuki Yamamoto" , "Quantity"] = 12
df.loc[df["CustomerName"] == "Yuki Yamamoto"]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,12,55.0,2024-07-06,Yes,Japan

In [ ]:
# Changing values of an entire column 
 
df["Country"] =  df["Country"].str.upper()

In [42]:
print(set(df["Country"]))

{'PORTUGAL', 'MEXICO', 'JAPAN', 'USA', 'FRANCE', 'ARGENTINA', 'CHINA', 'BRAZIL', 'GERMANY', 'UAE', 'AUSTRALIA', 'SINGAPORE', 'ITALY', 'SWEDEN', 'UKRAINE', 'PAKISTAN', 'POLAND', 'SPAIN', 'EGYPT', 'IRAN', 'RUSSIA', 'COLOMBIA', 'MOROCCO', 'UK', 'SOUTH KOREA', 'INDIA', 'SAUDI ARABIA', 'CANADA'}

In [44]:
# DELETING DATA

#deleting by index
df = df.drop(39)

In [ ]:
df.tail()

In [ ]:
# Dropping null values
df.dropna()

In [ ]:
# Filling null values 
df.fillna({"OrderID" : -1} , inplace = True)
# argument "inplace : True" means it's going to modify thexisting dataframe 
# and not create a new one

In [ ]:
#renaming columns 
df.rename(columns ={"OrderID" : "Order ID"} , inplace = True)

In [ ]:

# Analyzing Data

In [ ]:
df["Country"].value_counts()
#counts the occurences of a value of a specific column

In [ ]:
# Groupong by certain attributes 
df.groupby("Country")

In [76]:
(df.groupby(["Country" , "Product"])["Price"].sum() * df.groupby(["Country" , "Product"])["Quantity"].sum()) 
# Searching the values (money) generated from each product in each country

Country       Product
ARGENTINA     Desk Chair Mat             22.0
AUSTRALIA     Stapler                    36.0
BRAZIL        Bluetooth Speaker          95.0
CANADA        Headphones                300.0
              Highlighters               28.0
CHINA         Bookshelf                 280.0
COLOMBIA      Desk Drawer Organizer      42.0
EGYPT         Printer Paper             160.0
FRANCE        Paper Shredder             75.0
              Webcam                     85.0
GERMANY       Document Scanner          140.0
              Office Plant               70.0
INDIA         File Cabinet              360.0
IRAN          Desk Pad                   28.0
ITALY         Desk Calendar              18.0
              Pen                        15.0
JAPAN         Calculator                 15.0
              Monitor Stand             660.0
              Mouse                      35.0
MEXICO        Keyboard                  160.0
MOROCCO       USB Hub                    32.0
PAKISTAN      Sticky Notes               60.0
POLAND        Wireless Mouse             90.0
PORTUGAL      Wireless Earbuds          125.0
RUSSIA        Binder Clips               30.0
SAUDI ARABIA  Whiteboard                120.0
SINGAPORE     Desk Lamp                 135.0
SOUTH KOREA   Monitor                   440.0
              Power Strip                36.0
              Wireless Keyboard         110.0
SPAIN         USB Drive                 125.0
SWEDEN        Tablet Stand               28.0
UAE           Notebook                   25.0
              Office Chair              300.0
UK            Desk Lamp with USB         68.0
              Standing Desk             450.0
USA           Desk Organizer             65.0
              Index Cards                80.0
              Laptop                   1200.0
dtype: float64

In [89]:
(df.groupby(["Category","Country"])["Price"].sum() * df.groupby(["Category","Country"])["Quantity"].sum()).sort_values(ascending=False)
# sort_values() , sorting values in ascending or descending order 

# Values generated by each category in each country

Category     Country
Electronics  SOUTH KOREA     1740.0
             JAPAN           1470.0
             USA             1200.0
Furniture    UK              1036.0
             INDIA            360.0
Electronics  FRANCE           320.0
             CANADA           300.0
Furniture    UAE              300.0
             CHINA            280.0
Electronics  MEXICO           160.0
Stationery   EGYPT            160.0
Electronics  GERMANY          140.0
Furniture    SINGAPORE        135.0
Electronics  SPAIN            125.0
             PORTUGAL         125.0
Furniture    SAUDI ARABIA     120.0
Electronics  BRAZIL            95.0
             POLAND            90.0
Stationery   USA               80.0
Furniture    GERMANY           70.0
             USA               65.0
Stationery   PAKISTAN          60.0
Furniture    COLOMBIA          42.0
Stationery   AUSTRALIA         36.0
Electronics  MOROCCO           32.0
Stationery   RUSSIA            30.0
Electronics  SWEDEN            28.0
Stationery   CANADA            28.0
Furniture    IRAN              28.0
Stationery   UAE               25.0
Furniture    ARGENTINA         22.0
             ITALY             18.0
Stationery   ITALY             15.0
dtype: float64

In [ ]:
print(df["Country"])

   Order ID   CustomerName       Product     Category  Quantity   Price  \
0      1001     John Smith        Laptop  Electronics         1  1200.0
1      1002      Sarah Lee    Headphones  Electronics         2   150.0
2      1003       Ali Khan  Office Chair    Furniture         1   300.0
3      1004     Alice Wong     Desk Lamp    Furniture         3    45.0
4      1005  Carlos Mendez      Keyboard  Electronics         2    80.0

    OrderDate Shipped    Country
0  2024-06-01     Yes        USA
1  2024-06-03      No     CANADA
2  2024-06-04     Yes        UAE
3  2024-06-05     Yes  SINGAPORE
4  2024-06-06      No     MEXICO